Vagrant.configure("2") do |config|
  config.vm.define "nodo1" do |nodo1|
    nodo1.vm.box = "bento/ubuntu-16.04"
    nodo1.vm.network "private_network", ip:"192.168.33.11"
    nodo1.vm.hostname = "jenkins1"
    nodo1.vm.provider "virtualbox" do |vm|
      vm.name = "jenkins1"
      vm.memory = "256"
      vm.cpus = "1"
    end
  end
  config.vm.define "nodo2" do |nodo2|
    nodo2.vm.box = "bento/ubuntu-16.04"
    nodo2.vm.network "private_network", ip:"192.168.33.12"
    nodo2.vm.hostname = "jenkins2"
    nodo2.vm.provider "virtualbox" do |vm|
      vm.name = "jenkins2"
      vm.memory = "256"
      vm.cpus = "1"
    end
  end
end
