---
- hosts: server-jenkins
  remote_user: root
  tasks:
    - name: Agregar repositorio Java
      ansible.builtin.apt_repository:
        repo: ppa:openjdk-r/ppa
    - name: Instalar Java
      apt: name=openjdk-11-jdk state=present
    - name: Revisar Java
      shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
      changed_when: False
      register: java_result
    - debug:
        msg: "Java: {{ java_result.stdout }}"
    - name: Agregar llave de Jenkins
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present
    - name: Agregar repo de Jenkins en SourceList
      ansible.builtin.apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
    - name: Instalar Jenkins
      apt:
        name: jenkins
        update_cache: yes
        state: present
    - name: Estado Jenkins
      shell: service jenkins status
      changed_when: False
      register: jenkins_status
    - debug:
        msg: "Jenkins Status: {{ jenkins_status.stdout }}"
    - name: Esperar que la config de Jenkins se cree
      wait_for:
        path: /var/lib/jenkins/secret.key
    - name: Llave Jenkins
      shell: cat /var/lib/jenkins/secret.key
      changed_when: False
      become: True
      register: jenkins_key
    - debug:
        msg: "Jenkins Key: {{ jenkins_key.stdout }}"